spring.application.name=music-chain

# Server port
server.port=8080

# Logging
logging.level.com.musicchain=INFO
logging.level.org.springframework.web=WARN

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent-output=true

# Static resources served from /static
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**


lastfm.api.key = 23b893c8d8748cabbee17e209b31adc6